create_input_text:
  name: "Create an Enhanced Input Text Blob"
  description: "Create or update an enhanced input text entity."
  fields:
    name:
      name: "Name"
      description: "The name of the enhanced input text entity."
      example: "my_text"
      required: true
      selector:
        text:
    title:
      name: "Title"
      description: "The title to display as the state of the enhanced input text entity."
      example: "My Title"
      selector:
        text:
    text:
      name: "Text"
      description: "The long text to store in the enhanced input text entity."
      example: "This is a long text."
      selector:
        text:

delete_input_text:
  name: "Delete an Enhanced Input Text Blob"
  description: "Delete an enhanced input text entity."
  fields:
    name:
      name: "Name"
      description: "The name of the enhanced input text entity to delete."
      example: "my_text"
      required: true
      selector:
        text:
